# @package _global_

defaults:
  - config
  - override /vit_latent_scaling/preset: cifar10_50k

vit_latent_scaling:
  lr: 1e-2
  max_steps: 30000
  big_vae_decode: weights
  big_vae_tile_T_patches: 2
  big_vae_tile_d_out: 64
