from __future__ import annotations

from training.big_vae.batch_debug import *
from training.big_vae.batch_padding import *
from training.big_vae.data_types import *
from training.big_vae.presliced import *
from training.big_vae.source_sampling import *
from training.big_vae.source_state import *

__all__ = [
    '_identity_sample_collate',
    '_sample_list_collate',
    '_offline_loader_worker_init_fn',
    '_flatten_loader_batches',
    'SourceSampleRecord',
    'SourceSliceState',
    'ConsumedSourceBatch',
    'PreparedTrainingBatch',
    'PreslicedSliceRecord',
    '_source_sample_record_to_device',
    '_normalize_batch_source_uniqueness',
    '_source_sample_uniqueness_key',
    '_next_valid_source_sample',
    '_prepare_cpu_sample_tensor',
    '_broadcast_tensor_2d',
    '_fetch_batch_cpu',
    '_fetch_source_sample_record_cpu',
    '_fetch_batch',
    '_fetch_source_samples',
    '_prepare_cpu_bool_mask',
    '_next_valid_presliced_slice',
    '_compute_presliced_batch_source_diversity_stats',
    '_fetch_presliced_training_batch_cpu',
    '_sample_synthetic_layer',
    '_round_robin_source_indices',
    '_compute_batch_source_diversity_stats',
    '_pad_x_rows_with_mask',
    '_pad_d_in_with_mask',
    '_pad_d_out_with_mask',
    '_materialize_padded_slice_batch',
    '_slice_sample',
    '_build_without_replacement_index_groups',
    '_make_source_slice_state',
    '_remaining_source_state_slices',
    '_source_state_slice_shape',
    '_source_state_shape_capacities',
    '_max_source_state_shape_capacity',
    '_dominant_source_state_shape',
    '_prune_source_states_to_shape',
    '_source_states_total_remaining_slices',
    '_prune_exhausted_source_states',
    '_prune_exhausted_source_states_with_offset',
    '_source_states_uniqueness_keys',
    '_consume_slice_from_source_state',
    '_compute_consumed_batch_source_diversity_stats',
    '_build_training_batch_from_source_states',
    '_build_training_batch_from_source_samples',
    '_ensure_source_state_pool_capacity',
    '_compute_curriculum_slice_sizes',
    '_stable_batch_shape_targets',
    '_tensor_debug_stats',
    '_pin_tensor_if_available',
    '_pin_prepared_training_batch',
    '_scalar_debug_value',
]
