# @package _global_

vit_latent_scaling:
  init_name: base
  run_name: latent_base
  big_vae_latent_init: base
  require_raw_checkpoint: false
  require_diffusion_prior_checkpoint: false
  require_latent_checkpoint: false
